# Generated by Django 2.0.1 on 2018-08-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spikeapp', '0002_auto_20180808_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('index',), 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.RemoveField(
            model_name='creditcardpayment',
            name='expiry_month',
        ),
        migrations.RemoveField(
            model_name='creditcardpayment',
            name='expiry_year',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='currency',
        ),
        migrations.AddField(
            model_name='payment',
            name='index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
