# Generated by Django 2.0.1 on 2018-08-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spikeapp', '0004_auto_20180808_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sepapayment',
            name='destination',
        ),
        migrations.AddField(
            model_name='sepapayment',
            name='beneficiaries',
            field=models.ManyToManyField(blank=True, related_name='sepa', to='spikeapp.Beneficiary'),
        ),
    ]
