# Generated by Django 2.0.1 on 2018-08-08 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spikeapp', '0005_auto_20180808_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('title',), 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
