# Generated by Django 2.0.1 on 2018-08-08 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spikeapp', '0006_auto_20180808_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPayment',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='spikeapp.Payment')),
                ('title', models.CharField(max_length=34)),
                ('beneficiaries', models.ForeignKey(blank=True, on_delete='test', to='spikeapp.Beneficiary')),
            ],
            options={
                'verbose_name': 'Test Payment',
                'verbose_name_plural': 'Test Payments',
            },
            bases=('spikeapp.payment',),
        ),
    ]
